set-option -g xterm-keys on

# Start window numbering at 1
set-option -g base-index 1
set-window-option -g pane-base-index 1

# Enable mouse
set -g mouse on

# Scrolling works as expected
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

# Set tmux to use 256 color (needed for truecolor)
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Use the system clipboard (requried for MacOS)
set-option -g default-command "reattach-to-user-namespace -l $SHELL"

# split panes using v and s
bind v split-window -h
bind s split-window -v
unbind '"'
unbind %

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L; refresh-client -S
bind -n M-Right select-pane -R; refresh-client -S 
bind -n M-Up select-pane -U; refresh-client -S
bind -n M-Down select-pane -D; refresh-client -S

# Use vim keybindings in copy mode
set-window-option -g mode-keys vi

# Bind bind-key / to search
bind-key / copy-mode \; send-key ?

# Bind bind-key P to dump buffer to file (tmp/tmux)
bind-key P 'capture-pane' \; capture-pane -S - \; save-buffer /tmp/tmux \; delete-buffer

# Low escape time
set -sg escape-time 0

# Theme
source ~/.tmux.theme

#### PLUGINS
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'thewtex/tmux-mem-cpu-load'
#### PLUGINS

setenv -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.tmux/plugins/"

if "test ! -d ~/.tmux/plugins/tpm" \
  "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && \
      ~/.tmux/plugins/tpm/bin/install_plugins'"

run -b '~/.tmux/plugins/tpm/tpm'
