# This tmux statusbar config was created by tmuxline.vim
# on Fri, 14 Mar 2025
#
# With modifications

setenv -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.tmux/plugins/"

set -g status-justify "left"
set -g status "on"
set -g status-left-style "none"
set -g message-command-style "fg=#C1A78E,bg=#34302C"
set -g status-right-style "none"
set -g pane-active-border-style "fg=#C1A78E"
set -g status-style "none,bg=#34302C"
set -g message-style "fg=#C1A78E,bg=#34302C"
set -g pane-border-style "fg=#34302C"
set -g status-right-length "100"
set -g status-left-length "100"
setw -g window-status-activity-style "none"
setw -g window-status-separator ""
setw -g window-status-style "none,fg=#C1A78E,bg=#34302C"

set -g status-left "#[fg=#34302C,bg=#C1A78E] #(curl icanhazip.com) #[fg=#C1A78E,bg=#34302C,nobold,nounderscore,noitalics]#{simple_git_status}"
set -g status-right "#[fg=#867462,bg=#34302C,nobold,nounderscore,noitalics]#[fg=#34302C,bg=#867462] #(kubectl config current-context)  #(uptime | cut -f 4-5 -d ' ' | cut -f 1 -d ',') #[fg=#C1A78E,bg=#867462,nobold,nounderscore,noitalics]#[fg=#34302C,bg=#C1A78E] %R %a"

setw -g window-status-format "#[fg=#C1A78E,bg=#34302C] #I #[fg=#C1A78E,bg=#34302C] #W "
setw -g window-status-current-format "#[fg=#34302C,bg=#C1A78E,nobold,nounderscore,noitalics]#[fg=#34302C,bg=#C1A78E] #I #[fg=#34302C,bg=#C1A78E] #W #[fg=#C1A78E,bg=#34302C,nobold,nounderscore,noitalics]"
